-   id: fallow
    name: fallow
    description: ''
    entry: fallow
    language: node
    'types_or': [javascript, ts, tsx]
    args: []
    require_serial: true
    additional_dependencies: ["fallow@2.45.0"]
    minimum_pre_commit_version: '2.9.2'
