name: main
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
  - cron: '15 8 * * *'

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
    - run: uv tool install pre-commit-mirror-maker
    - run: git config --global user.name 'Github Actions'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - run: pre-commit-mirror . --language node --package-name fallow --types-or javascript --types-or ts --types-or tsx --require-serial
    - run: |
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/s-weigand/pre-commit-mirrors-fallow
        git push origin HEAD:refs/heads/main --tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
